STATES = [
    {'abbr': 'US',   'name': 'United States',      'demonym': 'American'        , 'level': "NAT",                       "alt": ('United States-Total'),},
    {'abbr': 'AK',   'name': 'Alaska',             'demonym': 'Alaskan'         , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'AL',   'name': 'Alabama',            'demonym': 'Alabaman'        , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'AR',   'name': 'Arkansas',           'demonym': 'Arkansan'        , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'AZ',   'name': 'Arizona',            'demonym': 'Arizonian'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'CA',   'name': 'California',         'demonym': 'Californian'     , 'level': "STA",    'parent': "US",    "alt": (),},  
    {'abbr': 'CO',   'name': 'Colorado',           'demonym': 'Coloradan'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'CT',   'name': 'Connecticut',        'demonym': 'Connecticuter'   , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'DC',   'name': 'Washington, DC',     'demonym': 'Washingtonian'   , 'level': "MET",    'parent': "US",    "alt": ('District of Columbia'),},
    {'abbr': 'DE',   'name': 'Delaware',           'demonym': 'Delawarean'      , 'level': "STA",    'parent': "US",    "alt": (),},  
    {'abbr': 'FL',   'name': 'Florida',            'demonym': 'Floridian'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'GA',   'name': 'Georgia',            'demonym': 'Georgian'        , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'HI',   'name': 'Hawaii',             'demonym': 'Hawaiian'        , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'IA',   'name': 'Iowa',               'demonym': 'Iowan'           , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'ID',   'name': 'Idaho',              'demonym': 'Idahoan'         , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'IL',   'name': 'Illinois',           'demonym': 'Illinoisan'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'IN',   'name': 'Indiana',            'demonym': 'Indianian'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'KS',   'name': 'Kansas',             'demonym': 'Kansan'          , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'KY',   'name': 'Kentucky',           'demonym': 'Kentuckian'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'LA',   'name': 'Louisiana',          'demonym': 'Louisianan'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'MA',   'name': 'Massachusetts',      'demonym': 'Massachusite'    , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'MD',   'name': 'Maryland',           'demonym': 'Marylander'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'ME',   'name': 'Maine',              'demonym': 'Mainer'          , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'MI',   'name': 'Michigan',           'demonym': 'Michigander'     , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'MN',   'name': 'Minnesota',          'demonym': 'Minnesotan'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'MO',   'name': 'Missouri',           'demonym': 'Missourian'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'MS',   'name': 'Mississippi',        'demonym': 'Mississippian'   , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'MT',   'name': 'Montana',            'demonym': 'Montanan'        , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'NC',   'name': 'North Carolina',     'demonym': 'North Carolinian', 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'ND',   'name': 'North Dakota',       'demonym': 'North Dakotan'   , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'NE',   'name': 'Nebraska',           'demonym': 'Nebraskan'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'NH',   'name': 'New Hampshire',      'demonym': 'New Hampshirite' , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'NJ',   'name': 'New Jersey',         'demonym': 'New Jerseyan'    , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'NM',   'name': 'New Mexico',         'demonym': 'New Mexican'     , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'NV',   'name': 'Nevada',             'demonym': 'Nevadan'         , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'NY',   'name': 'New York',           'demonym': 'New Yorker'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'OH',   'name': 'Ohio',               'demonym': 'Ohioan'          , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'OK',   'name': 'Oklahoma',           'demonym': 'Oklahoman'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'OR',   'name': 'Oregon',             'demonym': 'Oregonian'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'PA',   'name': 'Pennsylvania',       'demonym': 'Pennsylvanian'   , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'RI',   'name': 'Rhode Island',       'demonym': 'Rhode Islander'  , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'SC',   'name': 'South Carolina',     'demonym': 'South Carolinian', 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'SD',   'name': 'South Dakota',       'demonym': 'South Dakotan'   , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'TN',   'name': 'Tennessee',          'demonym': 'Tennessean'      , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'TX',   'name': 'Texas',              'demonym': 'Texan'           , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'UT',   'name': 'Utah',               'demonym': 'Utahn'           , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'VA',   'name': 'Virginia',           'demonym': 'Virginian'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'VT',   'name': 'Vermont',            'demonym': 'Vermonter'       , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'WA',   'name': 'Washington',         'demonym': 'Washingtonian'   , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'WI',   'name': 'Wisconsin',          'demonym': 'Wisconsinite'    , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'WV',   'name': 'West Virginia',      'demonym': 'West Virginian'  , 'level': "STA",    'parent': "US",    "alt": (),},
    {'abbr': 'WY',   'name': 'Wyoming',            'demonym': 'Wyomingite'      , 'level': "STA",    'parent': "US",    "alt": (),},
]

def getStateAbbr(statename):
    statedict = filter(lambda x: x['name'] == statename, STATES)
    if not statedict:
        statedict = filter(lambda x: statename in x['alt'], STATES)
    return statedict[0]['abbr'] if statedict else False
